export const AppPaths = {
    home: '/',
    authorization: '/account/authorize',
    profile: '/account/profile',
    accountOrders: '/account/orders',
    gameDetails: '/game/details',
    shoppingCart: '/cart',
    gameSearch: '/game/search',
    gameCatalog: '/game/catalog',
    payment: '/payment',
    orderDetails: '/orders/order-details',
    manager: '/manager',
    editGame: '/manager/edit',
    createGame: '/manager/create',
}