<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<ProjectReference Include="..\DAL\DAL.csproj" />
		<ProjectReference Include="..\Exceptions\Exceptions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Braintree" Version="5.16.0" />
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="MimeKit" Version="4.15.1" />
		<PackageReference Include="Ninject" Version="3.3.6" />
	</ItemGroup>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
</Project>