<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
		<IsPackable>false</IsPackable>
		<SpaRoot>..\clientapp\</SpaRoot>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
		<SpaProxyServerUrl>http://localhost:3000</SpaProxyServerUrl>
		<SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageId>ClassLibDotNetStandard</PackageId>
		<Version>1.0.0</Version>
		<Company>Namerek inc.</Company>
		<Product>GameStore.gg</Product>
		<Title>API</Title>
		<FileVersion>1.0.0.5</FileVersion>
		<AssemblyVersion>1.0.0.5</AssemblyVersion>
		<UserSecretsId>79a3edd0-2092-40a2-a04d-dcb46d5ca9ed</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="10.0.5" />
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="10.0.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MimeKit" Version="4.15.1" />
		<PackageReference Include="Ninject" Version="3.3.6" />
		<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="7.0.0" />
	</ItemGroup>
	<ItemGroup>
		<Content Remove="$(SpaRoot)**" />
		<Content Remove="obj\**" />
		<None Remove="$(SpaRoot)**" />
		<None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="obj\**" />
	  <EmbeddedResource Remove="obj\**" />
	  <None Remove="..\clientapp\obj\**" />
	  <None Remove="..\clientapp\public\**" />
	  <None Remove="..\clientapp\src\**" />
	  <None Remove="obj\**" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="..\clientapp\.env" />
	  <None Remove="..\clientapp\.env.development" />
	  <None Remove="..\clientapp\.env.development.local" />
	  <None Remove="..\clientapp\.gitignore" />
	  <None Remove="..\clientapp\aspnetcore-https.js" />
	  <None Remove="..\clientapp\aspnetcore-react.js" />
	  <None Remove="..\clientapp\clientapp.esproj" />
	  <None Remove="..\clientapp\clientapp.esproj.user" />
	  <None Remove="..\clientapp\nuget.config" />
	  <None Remove="..\clientapp\package-lock.json" />
	  <None Remove="..\clientapp\package.json" />
	  <None Remove="..\clientapp\README.md" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\BLL\BLL.csproj" />
		<ProjectReference Include="..\clientapp\clientapp.esproj" Condition="'$(OS)' == 'Windows_NT'">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<Folder Include="wwwroot\files\game images\" />
	</ItemGroup>
	<Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
		<Exec Command="node --version" ContinueOnError="true">
			<Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
		</Exec>
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
		<Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and then restart your command prompt or IDE." />
		<Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
	</Target>
	<Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
		<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build" />
		<ItemGroup>
			<DistFiles Include="$(SpaRoot)build\**" />
			<ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
				<RelativePath>wwwroot\%(RecursiveDir)%(FileName)%(Extension)</RelativePath>
				<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
				<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			</ResolvedFileToPublish>
		</ItemGroup>
	</Target>
</Project>